#ifndef H_SerializerBase
#define H_SerializerBase
#include <cstdint>
#include "ObjectSerialization/Serializable.hpp"
#include "stream.hpp"

namespace bfu
{

	#define SERIALIZER_SECTION __attribute__((section(".Serializer")))
	#define DESERIALIZER_SECTION __attribute__((section(".Deserializer")))

#define GENERATE_SERIALIZE_FUNCTIONS_FOR_SINGLE_VAR(T) \
	virtual void SERIALIZER_SECTION Serialize( T* data ) = 0; \
	static void SERIALIZER_SECTION Serialize_##T (SerializerBase* serializer, void* data); \


#define GENERATE_SERIALIZE_FUNCTIONS_FOR_VAR_VECTOR(T) \
	virtual void SERIALIZER_SECTION Serialize( SerializableVector<T>* data ) = 0; \
	static void SERIALIZER_SECTION Serialize_v_##T (SerializerBase* serializer, void* data); \



#define GENERATE_DESERIALIZE_FUNCTIONS_FOR_SINGLE_VAR(T) \
	virtual void DESERIALIZER_SECTION Deserialize( T* data ) = 0; \
	static void DESERIALIZER_SECTION Deserialize_##T (SerializerBase* serializer, void* data); \

#define GENERATE_DESERIALIZE_FUNCTIONS_FOR_VAR_VECTOR(T) \
	virtual void DESERIALIZER_SECTION Deserialize( SerializableVector<T>* data ) = 0; \
	static void DESERIALIZER_SECTION Deserialize_v_##T (SerializerBase* serializer, void* data); \

	class SerializableClassInterface;

	using bfu::stream;
	using bfu::string;

	class SerializerBase
	{
	public:

		virtual char* data() = 0;
		virtual int size() = 0;
		virtual void clear() = 0;
		virtual void assignData(char* data, uint32_t size) = 0;

		GENERATE_SERIALIZE_FUNCTIONS_FOR_SINGLE_VAR( SerializableClassInterface )
		GENERATE_SERIALIZE_FUNCTIONS_FOR_SINGLE_VAR( float )
		GENERATE_SERIALIZE_FUNCTIONS_FOR_SINGLE_VAR( bool )
		GENERATE_SERIALIZE_FUNCTIONS_FOR_SINGLE_VAR( stream )
		GENERATE_SERIALIZE_FUNCTIONS_FOR_SINGLE_VAR( string )
		GENERATE_SERIALIZE_FUNCTIONS_FOR_SINGLE_VAR( uint8_t )
		GENERATE_SERIALIZE_FUNCTIONS_FOR_SINGLE_VAR( uint16_t )
		GENERATE_SERIALIZE_FUNCTIONS_FOR_SINGLE_VAR( uint32_t )
		GENERATE_SERIALIZE_FUNCTIONS_FOR_SINGLE_VAR( uint64_t )
		GENERATE_SERIALIZE_FUNCTIONS_FOR_SINGLE_VAR( int8_t )
		GENERATE_SERIALIZE_FUNCTIONS_FOR_SINGLE_VAR( int16_t )
		GENERATE_SERIALIZE_FUNCTIONS_FOR_SINGLE_VAR( int32_t )
		GENERATE_SERIALIZE_FUNCTIONS_FOR_SINGLE_VAR( int64_t )


		virtual void SERIALIZER_SECTION Serialize( SerializableVector<SerializableClassInterface>* data ) = 0; 
		static void SERIALIZER_SECTION Serialize_v_SerializableClassInterface (SerializerBase* serializer, void* data); 
		GENERATE_SERIALIZE_FUNCTIONS_FOR_VAR_VECTOR( float )
		GENERATE_SERIALIZE_FUNCTIONS_FOR_VAR_VECTOR( bool )
		GENERATE_SERIALIZE_FUNCTIONS_FOR_VAR_VECTOR( stream )
		GENERATE_SERIALIZE_FUNCTIONS_FOR_VAR_VECTOR( string )
		GENERATE_SERIALIZE_FUNCTIONS_FOR_VAR_VECTOR( uint8_t )
		GENERATE_SERIALIZE_FUNCTIONS_FOR_VAR_VECTOR( uint16_t )
		GENERATE_SERIALIZE_FUNCTIONS_FOR_VAR_VECTOR( uint32_t )
		GENERATE_SERIALIZE_FUNCTIONS_FOR_VAR_VECTOR( uint64_t )
		GENERATE_SERIALIZE_FUNCTIONS_FOR_VAR_VECTOR( int8_t )
		GENERATE_SERIALIZE_FUNCTIONS_FOR_VAR_VECTOR( int16_t )
		GENERATE_SERIALIZE_FUNCTIONS_FOR_VAR_VECTOR( int32_t )
		GENERATE_SERIALIZE_FUNCTIONS_FOR_VAR_VECTOR( int64_t )



		GENERATE_DESERIALIZE_FUNCTIONS_FOR_SINGLE_VAR( SerializableClassInterface )
		GENERATE_DESERIALIZE_FUNCTIONS_FOR_SINGLE_VAR( float )
		GENERATE_DESERIALIZE_FUNCTIONS_FOR_SINGLE_VAR( bool )
		GENERATE_DESERIALIZE_FUNCTIONS_FOR_SINGLE_VAR( stream )
		GENERATE_DESERIALIZE_FUNCTIONS_FOR_SINGLE_VAR( string )
		GENERATE_DESERIALIZE_FUNCTIONS_FOR_SINGLE_VAR( uint8_t )
		GENERATE_DESERIALIZE_FUNCTIONS_FOR_SINGLE_VAR( uint16_t )
		GENERATE_DESERIALIZE_FUNCTIONS_FOR_SINGLE_VAR( uint32_t )
		GENERATE_DESERIALIZE_FUNCTIONS_FOR_SINGLE_VAR( uint64_t )
		GENERATE_DESERIALIZE_FUNCTIONS_FOR_SINGLE_VAR( int8_t )
		GENERATE_DESERIALIZE_FUNCTIONS_FOR_SINGLE_VAR( int16_t )
		GENERATE_DESERIALIZE_FUNCTIONS_FOR_SINGLE_VAR( int32_t )
		GENERATE_DESERIALIZE_FUNCTIONS_FOR_SINGLE_VAR( int64_t )


		virtual void DESERIALIZER_SECTION Deserialize( SerializableVector<SerializableClassInterface>* data ) = 0; 
		static void DESERIALIZER_SECTION Deserialize_v_SerializableClassInterface (SerializerBase* serializer, void* data); 
		GENERATE_DESERIALIZE_FUNCTIONS_FOR_VAR_VECTOR( float )
		GENERATE_DESERIALIZE_FUNCTIONS_FOR_VAR_VECTOR( bool )
		GENERATE_DESERIALIZE_FUNCTIONS_FOR_VAR_VECTOR( stream )
		GENERATE_DESERIALIZE_FUNCTIONS_FOR_VAR_VECTOR( string )
		GENERATE_DESERIALIZE_FUNCTIONS_FOR_VAR_VECTOR( uint8_t )
		GENERATE_DESERIALIZE_FUNCTIONS_FOR_VAR_VECTOR( uint16_t )
		GENERATE_DESERIALIZE_FUNCTIONS_FOR_VAR_VECTOR( uint32_t )
		GENERATE_DESERIALIZE_FUNCTIONS_FOR_VAR_VECTOR( uint64_t )
		GENERATE_DESERIALIZE_FUNCTIONS_FOR_VAR_VECTOR( int8_t )
		GENERATE_DESERIALIZE_FUNCTIONS_FOR_VAR_VECTOR( int16_t )
		GENERATE_DESERIALIZE_FUNCTIONS_FOR_VAR_VECTOR( int32_t )
		GENERATE_DESERIALIZE_FUNCTIONS_FOR_VAR_VECTOR( int64_t )


	};
}

#endif